spring:
  datasource:
    druid:
      initial-size: 8
      max-active: 64
      min-idle: 8
      max-wait: 60000
      remove-abandoned: true
      remove-abandoned-timeout-millis: 60
      log-abandoned: true
      max-pool-prepared-statement-per-connection-size: 8
      pool-prepared-statements: true
      validation-query: SELECT 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat,wall
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js , *.gif ,*.jpg ,*.png ,*.css ,*.ico , /druid/*"
        session-stat-max-count: 64
        profile-enable: true
        session-stat-enable: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
        allow: ""
        deny: ""