<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.gv.steel</groupId>
        <artifactId>user-system</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>user-system-api</artifactId>
    <packaging>jar</packaging>

    <description>user 模块 feign api</description>

    <dependencies>
        <!-- 公共工具模块 -->
        <dependency>
            <groupId>com.gv.steel</groupId>
            <artifactId>steel-common-core</artifactId>
        </dependency>

        <!-- mybatis 模块 -->
        <dependency>
            <groupId>com.gv.steel</groupId>
            <artifactId>steel-common-mybatis</artifactId>
        </dependency>

        <!--open feign 模块-->
        <dependency>
            <groupId>com.gv.steel</groupId>
            <artifactId>steel-common-feign</artifactId>
        </dependency>

        <!--swagger-->
        <dependency>
            <groupId>com.gv.steel</groupId>
            <artifactId>steel-common-swagger</artifactId>
        </dependency>

        <!--easy excel-->
        <dependency>
            <groupId>com.gv.steel</groupId>
            <artifactId>steel-common-easyexcel</artifactId>
        </dependency>
    </dependencies>

</project>
